version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  kafka:
    image: wurstmeister/kafka:0.10.1.0
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  train-registry:
    image: registry:2.6.2
    name: train-registry
    hostname: train-registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - "${PHT_TRAINREGISTRY_CERT_DOMAIN:?No domain.crt provided}:/certs/domain.crt"
      - "${PHT_TRAINREGISTRY_CERT_KEY:?No domain.key provided}:/certs/domain.key"
      - "${PHT_TRAINREGISTRY_CONFIG_FILE:?No config file provided}:/etc/docker/registry/config.yml"
    ports:
      "443:443"

  eureka-server:
    image: pht/eureka-server:0.0.1-SNAPSHOT
    expose:
     - "8761"
